export interface ICalculatorProps {
    onCalculatorChanged?(): void;
    decimals: number;
    insuranceDescription: string;
    periodStep: number;
    footerText: string,
    insuranceDescriptionWithPpi: string,
    insuranceText: string,
    insuranceEnabled: boolean,
    coApplicantText: string,
    details: string,
    applyButtonText: string,
    totalDebtInfo: string;
    totalDebtHeading: string,
    includeDebt: boolean,
    isOnLoanPage: boolean,
    amountCoApplicantText: string;
    amountEnabled: boolean;
    amountStep: number;
    amountText: string;
    baseInterest: number;
    baseInterestText: string;
    coApplicantAmountThreshold: number;
    coApplicantEnabled: boolean;
    costText: string;
    defaultAmount: number;
    defaultPeriod: number;
    extraMarkerPoint: number;
    fixedStartFee: number;
    highInterestText: string;  
    highRepaymentMinimumPeriod: number;
    highRepaymentText: string;
    informationText: string;
    interestHigh: number;
    interestLow: number;
    lowInterestText: string;
    maximumAmount: number;
    maximumPeriod: number;
    maximumInstallment: number;
    maximumInstallmentExceededMessage: string;
    minimumAmount: number;
    minimumMonthlyInsurance: number;
    minimumPeriod: number;
    monthlyPayment: number;
    monthlyPaymentPercentage: number;
    periodDisplayInYears: number;
    periodText: string;
    ppi: number;
    showPurposeOfLoan: boolean;
    showAsButtons: boolean; 
    startFee: number;
}